#+TAGS: SPORT(s) OBJECTS(o)


* Sports                                                              :SPORT:

** Sport in your country

Besides the sport you just spoke about, what other sports are popular in your country? FQ

Are there any differences between the popularity of sports in your country today and the situation in the past? FQ

(Similar to above) In your country, have people's attitudes towards sport changed at all over the past few decades? FQ

Do people play sport very much in your country?

Why do some people not like sport? FQ

(Similar to above) What are some people not very interested in sport? FQ

Do you play any sport yourself?

Do women play sport very much?

Do you think women's sport will change in the future?

Does the government in your country have much influence over sport?

** The Olympic Games

At the Olympic Games, do athletes from your country do better (= win more medals) in individual sports or team sports?

Do you think the Olympic Games is becoming (or, has become) too commercialized?

Do you think there should be any restrictions on advertising during the Olympic Games?   See Note

** Professional Sports and Sports Stars

Do you have a favourite sportsperson?

(Similar to above) Can you give me any examples of famous sportsmen or women (famous athletes)?

(Similar to above) Can you give me any examples of professional athletes (professional sportsmen and women)?

Do you think there is much difference between famous athletes today and those of the past?

Do you think some of these professional athletes are overpaid? *

Do you think these highly paid athletes deserve to receive so much money? *

Where does the money come from to pay these professional athletes? *

Why do so many teenage males (and boys and even some young females) dream of being a professional athlete (or, a sports star)? FQ

Do you think some people become top sportspeople by hard work (or, effort) or is it more a question of good luck?  FQ

Do many young people in your country aspire to being a professional athlete?

Do you think it's possible for everyone (or, anyone) to duplicate the success of those professional athletes?

Do many children (and/ or young people) use professional sportspeople as models to copy? FQ

Would you say that's a good thing? FQx2

Do you think professional athletes set a good example for young people?

Do you think professional athletes should set a good example for young people?

* Equipment & Modern Technology                                     :OBJECTS:

** The Quality of Products / Equipment that Breaks Easily

In your country, what are some examples of equipment that often breaks down or becomes
unusable because of some fault?

Why do you think this equipment breaks so easily? 

Why do some devices (or why does some some equipment) break down? 

Why do people have problems with some equipment? 

Do people in your country usually throw away broken equipment or do they usually get it
repaired (or try to repair it themselves)?

** Equipment Used in Everyday Life

What are some examples of equipment (or machines, or devices) that we use in everyday
life?

Which of those do you think is the most important?

Which of those would you say are essential to have?

Do you think modern, labour-saving devices/equipment make people lazy? 

How do you think people feel when they buy new (modern) equipment) such as a Smart Phone?

Do young people and old people have the same feelings (or attitudes) about modern
equipment?

** Electronic Equipment at school

What do you think of (the practice of students) using a cell phone to take pictures of
classroom notes (presented on a screen or whiteboard by the teacher or lecturer) instead of
using pen and paper?

** Electrical Appliances

Have (the item you chose to talk about) changed much over the years?

Do you think that (the item you chose to talk about) are important to society? (How?)

Do you think everyone needs to know how to use the item you chose to talk about?

What kinds of electrical appliances are most used in the home, (besides the telephone and
computer)? (Hints: washing machine; vacuum cleaner; rice cooker; iron; coffee maker;
electric kettle; water dispenser; food blender; microwave oven; hair dryer; air conditioner;
fan) FQ

How do these things help people? FQ

What are some examples of electronic or electrical equipment that are used for
communication? FQ

What are some examples of electronic or electrical equipment that are used for
entertainment (leisure)? FQ

What are some advantages and disadvantages of using electrical equipment? FQ

Do you think we can now live without electrical appliances? FQ

What's your opinion of this? Is that a good situation?

Do you think science and technology will one day completely eliminate traditional
technology and equipment?

What kinds of electrical or electronic appliances do you think we will have in the future?
( = How do you think electrical & electronic appliances will develop in the future?) FQ
(Hint: Difficult question. Think science fiction.)

Do you think computers will one day replace books?

The following was the examiner's own question, not listed in the question book. 

You say you download songs to your MP3. But if you like a singer, don't you think you
should support him/her by buying their CD's?

** Office Equipment 

What are some of the different forms of electronic communication that people use in
offices today and how are they useful? FQ

What are the effects of using such electronic forms of communication? (What are the
advantages & disadvantages of using these?)

(Similar to above) What are the advantages and disadvantages of using new technology in
the workplace? FQ

Today, people rely on hi-tech communication equipment. Do you think there are any dangers
or shortcomings to this reliance? FQ

What other tools are used in offices today?

Compare office equipment today with office equipment of years ago.  

How do you office equipment will change in the future? 

Do you think that advancements in office technology will result in fewer people or more
people working in offices in the future? FQ

(As above) What effects do you think the future use of electronic equipment will have on
employment? FQ

** Modern Technology & Human Progress 

What are the effects on people of modern technology such as television and computers? FQ

(Similar to above) What changes have taken place in society as a result of the use modern
technology such as the television and the computer? FQ

Do you think people rely too much on machines and modern technology nowadays?

What are the advantages that we get from using modern home and office equipment?

What do you think is the most useful thing that man has ever invented? 

Do you think being able to use advanced technology (e.g., computers) can help people when
they are looking for a job? 

Do you think computers will ever be intelligent enough to replace human brain power?

Do you think robots will replace humans for some types of work?

Do you think we will ever be able to truly communicate with robots?   

Is there a relationship between advancements in high technology and the true progress of
humanity? (Hint: Not really. Many advancements in high technology were first made for
military purposes.)

Do you think modern appliances have decreased the amount of housework that people have to
do?

Who does most of the housework in Chinese families, the husband or the wife?

How do you think electronics will develop in the future? (= What new electronic devices do
you think might be invented in the future?)

How do you think modern technology will change the way people work in the future? FQ

** Electrical Appliances in the Home

What electrical appliances do you (or people in China) have at home? FQx2 See Vocab. list
Also see Note

What do people use these appliances for (= what work do people do, using these
appliances)?

What benefits do people get from using these things? FQx2

(Similar to above) Do you think these things are important?

(Similar to above) Why do modern people use so many electrical appliances (work tools) in
the home?

(Similar to above) What electrical appliances (or, electrical equipment) that people use
in the home or office have made it easier for people to work or study?

Some people say that modern electrical appliances make people lazy. Do you agree?

Do you think there are any shortcomings or dangers to using electrical equipment in the
home? FQx2

Who do you think should carry the greatest responsibility for the safety of electrical
equipment in the home - the manufacturer of the product, the seller of the product, the user
of the product or the government?

What happens when there is a blackout? (= How do people manage when there is a blackout?)
FQ

(Similar to above) How did people manage before they had electrical appliances in the
home? FQ

(Similar to above) How was housework many decades ago different to housework today?

How has household equipment changed in China in the past few decades?

** Product Design 

Do you think the design of the products people use is important? For example, the design
of an electric kettle for boiling water?

Do you think the design of products (such as tools, furniture & appliances) is important
for children?

What do you think is the most important factor when considering the design of an
invention?

Which do you think is more useful, a simple design or a complex design? (Say why & include
a comparison of the two.) FQ

What tools(s) do home appliance designers use to do their work? See Note

To be a designer of home appliances, what qualities (or skills) do you think a person
needs to have? FQ

What do you understand the word, 'creativity' to mean?

Do you think children should be encouraged, in school, to develop their creativity,
innovation & artistic skills? FQ

How do you think this could be done?  

** Inventions and Technological Development

What do you think are some of the most useful inventions that have been made? FQ

How are the tools and equipment we use today different to those of several decades ago?

Do you think modern inventions are becoming simpler than before or more complex?

Would you say computers are 'user-friendly'?

(Besides the computer), what do you think has been the most important invention of
mankind? (Perhaps the computer is allowable as an answer - the question is unclear.)

What would you say is the best invention in your family home?

What skills and knowledge do you think people need to be an inventor?

How do you feel about modern science and technology? For example, do we really need to be
continuously presented with new products and new inventions? FQ

(Similar to above) Do you think it's good that new inventions are appearing so often (or,
so quickly) (in the shops or, in society)? FQ

Why do you think we are constantly being urged to buy new products? 

What are some of the major products that China produces?  

(Similar to above) What are some of the major products that are produced in your part of
China?  

Compare these products with similar products produced overseas.

If you were the manager of a company that had produced a new invention, how would you
promote it?

If a new invention were going to be used by many people, what kind of testing of this
product do you think would be necessary? (Hint: health & safety checks - give examples)

In what ways do you think technology will develop in the next, say, 20 or 30 years?

Do you think there will be any negative effects resulting from future technology?

What conditions will be necessary to encourage the future development of technology in
China? FQ

(Similar to above) If you were the leader of China, what would you do to promote the
development of technology in China?
